### ISSUE TITLE
export 'CheckableListItemBlock' was not found in './CheckableListItem

### ISSUE THREAD

**Issue by vegawong** [sugarshin/draft-js-checkable-list-item#19]
https://github.com/sugarshin/draft-js-checkable-list-item/blob/3a36e4f6ee27f5fcd0d1fcd2237dedfb9ffd17ac/src/index.js#L6

**Comment by brandontle** [comment]
Still an open issue, at least with npm package. 

https://github.com/sugarshin/draft-js-checkable-list-item/commit/3cfb6c4fff0f5b837b51e14eb745c52b6dff8fe4

**Comment by sugarshin** [comment]
Merged and new version published. https://github.com/sugarshin/draft-js-checkable-list-item/pull/21
